---
sidebar: sidebar 
permalink: release-notes/whats-new.html 
keywords: 'reports what"s new, bluexp' 
summary: Erfahren Sie, was an den BlueXP Migrationsberichten neu ist. 
---
= Was ist neu
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, was an den BlueXP Migrationsberichten neu ist.



== Bis 13. November 2023

Sie können jetzt Berichte für Volumes erstellen, die das SMB/CIFS-Protokoll verwenden.



== 03 September 2023

Der aktualisierte BlueXP Migrations-Reports-Service bietet Updates für die Berichtsdaten. Berichte enthalten jetzt die zugewiesene Kapazität.



== 02 Juni 2023

Mit dem neuen BlueXP Migrationsberichterstattung-Service können Sie die Anzahl an Dateien, Verzeichnissen, symbolischen Links, Hardlinks, die Tiefe und Breite der Filesystem-Strukturen, größten Dateien und mehr in Ihrer Storage-Landschaft schnell ermitteln.

Mit diesen Informationen wissen Sie vorab, dass der Prozess, den Sie verwenden möchten, Ihren Bestand effizient und erfolgreich handhaben kann.

link:https://docs.netapp.com/us-en/bluexp-reports/get-started/intro.html["Erfahren Sie mehr über die BlueXP Migrationsberichte"].
